-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpicePageTemplates/maintenance/db/sql/bs_pagetemplate.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE bs_pagetemplate (
  pt_id SERIAL NOT NULL,
  pt_label VARCHAR(255) DEFAULT '' NOT NULL,
  pt_desc VARCHAR(255) DEFAULT '' NOT NULL,
  pt_target_namespace INT DEFAULT -99 NOT NULL,
  pt_template_title TEXT DEFAULT '' NOT NULL,
  pt_template_namespace INT DEFAULT 0 NOT NULL,
  pt_sid INT DEFAULT 0 NOT NULL,
  PRIMARY KEY(pt_id)
);
