-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpicePageTemplates/db/bs_pagetemplate.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bs_pagetemplate (
  pt_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  pt_label VARBINARY(255) DEFAULT '' NOT NULL,
  pt_desc VARBINARY(255) DEFAULT '' NOT NULL,
  pt_target_namespace VARBINARY(255) DEFAULT '[-99]' NOT NULL,
  pt_template_title VARBINARY(255) DEFAULT '' NOT NULL,
  pt_template_namespace INT DEFAULT 0 NOT NULL,
  pt_sid INT UNSIGNED DEFAULT 0 NOT NULL,
  pt_tags VARBINARY(255) DEFAULT NULL,
  PRIMARY KEY(pt_id)
) /*$wgDBTableOptions*/;
