-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/BlueSpicePageTemplates/db/bs_pagetemplate_add_tags_col_patch.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/bs_pagetemplate
  ADD pt_tags VARBINARY(255) DEFAULT NULL;
